model:
  dino_model: dinov3_vith16plus 
  desc_layer: 28    #true_layer=desc_layer+1
  desc_facet: token 
  use_cls: false       
  aggre_type: GeM             
  save_dir: data/jzl/GeoAlign/feats_test_s2d

workers: 4

eval:
  dataset: U1652_Image_S2D
  data_path: autodl-tmp/University-Release/test
  batch_size: 64
  output: feat
  pos_eval: false
  refine: false
  transform:
    - ToTensor
    - normalize